"use client";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {downloadContractEvidence,fetchContractEvidences} from "@/modules/contracts/contract-evidence-client";
import {buildContractEvidenceRequirements,summarizeEvidenceRequirements} from "@/modules/contracts/contract-evidence-presenter";
import type {ContractEvidenceReadModel} from "@/modules/contracts/contract-evidence-read-model";
import {EvidenceRequirementCard} from "./evidence-requirement-card";

export function ContractEvidencePanel({contractId}:{contractId:string}){const [evidences,setEvidences]=useState<ContractEvidenceReadModel[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[downloadMessage,setDownloadMessage]=useState<string|null>(null),[downloadingId,setDownloadingId]=useState<string|null>(null);const requestRef=useRef(0);
  const load=useCallback(async()=>{const request=++requestRef.current;setLoading(true);setError(null);try{const next=await fetchContractEvidences(contractId);if(request===requestRef.current)setEvidences(next)}catch(cause){if(request===requestRef.current)setError(cause instanceof Error?cause.message:"Não foi possível carregar os documentos.")}finally{if(request===requestRef.current)setLoading(false)}},[contractId]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>{window.clearTimeout(timer);requestRef.current+=1}},[load]);const requirements=useMemo(()=>buildContractEvidenceRequirements(evidences),[evidences]);const summary=useMemo(()=>summarizeEvidenceRequirements(requirements),[requirements]);
  async function download(evidence:ContractEvidenceReadModel){if(!evidence.documentDownloadPath||downloadingId)return;setDownloadingId(evidence.evidenceId);setDownloadMessage(null);try{await downloadContractEvidence(evidence.documentDownloadPath);setDownloadMessage("Download iniciado com segurança.")}catch(cause){setDownloadMessage(cause instanceof Error?cause.message:"Não foi possível baixar o documento.")}finally{setDownloadingId(null)}}
  return <section aria-labelledby="contract-documents-title" className="grid gap-5"><div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold text-slate-950" id="contract-documents-title">Documentos do contrato</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Consulta de evidências e documentos privados. A presença de evidência não altera a situação do contrato nem produz efeito financeiro.</p></div><div aria-live="polite">{loading?<p className="rounded-xl border border-dashed border-slate-300 bg-white p-5 text-sm text-slate-600">Carregando documentos...</p>:null}{error?<div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-900" role="alert"><p>{error}</p><button className="mt-3 rounded-md border border-rose-300 bg-white px-3 py-2 font-semibold" onClick={()=>void load()} type="button">Tentar novamente</button></div>:null}{downloadMessage?<p className="rounded-xl border border-slate-200 bg-white p-3 text-sm text-slate-700">{downloadMessage}</p>:null}</div>{!loading&&!error?<><section aria-label="Síntese documental" className="grid gap-3 sm:grid-cols-3"><Metric label="Validadas" value={summary.validated}/><Metric label="Aguardando validação" value={summary.awaitingValidation}/><Metric label="Pendentes" value={summary.pending}/></section><div className="grid items-start gap-4 md:grid-cols-2 2xl:grid-cols-3">{requirements.map(requirement=><EvidenceRequirementCard requirement={requirement} downloadingId={downloadingId} key={requirement.type} onDownload={evidence=>void download(evidence)}/>)}</div></>:null}</section>;
}
function Metric({label,value}:{label:string;value:number}){return <article className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold text-slate-950">{value}</p></article>}
