"use client";
import {useState,type FormEvent} from "react";
import {ContractEvidenceClientError,createEvidenceIntentKey,uploadContractEvidence,type EvidenceUploadInput} from "@/modules/contracts/contract-evidence-client";
import type {ContractEvidenceType} from "@/modules/contracts/contract-evidence-read-model";

type UploadType=Extract<ContractEvidenceType,"signed_contract"|"first_installment_payment">;
export function ContractEvidenceUploadDialog({administratorId,administratorName,contractId,evidenceType,onClose,onRefresh,onConfirmed}:{administratorId:string|null;administratorName:string;contractId:string;evidenceType:UploadType;onClose:()=>void;onRefresh:(contractId:string)=>Promise<void>;onConfirmed:(contractId:string)=>Promise<void>}){
  const [idempotencyKey]=useState(createEvidenceIntentKey),[submitting,setSubmitting]=useState(false),[message,setMessage]=useState<string|null>(null);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(submitting)return;if(evidenceType==="first_installment_payment"&&!administratorId){setMessage("Este contrato não possui administradora vinculada.");return;}setSubmitting(true);setMessage(null);const data=new FormData(event.currentTarget);try{const input=buildInput(evidenceType,data,administratorId);const result=await uploadContractEvidence(contractId,input,idempotencyKey);if(result.kind==="outcome_unknown"){setMessage(result.message);await onRefresh(contractId);return;}await onConfirmed(contractId);}catch(cause){setMessage(cause instanceof Error?cause.message:"Não foi possível enviar o documento.");if(cause instanceof ContractEvidenceClientError&&cause.status===409)await onRefresh(contractId);}finally{setSubmitting(false)}}
  const missingAdministrator=evidenceType==="first_installment_payment"&&!administratorId;
  return <div aria-modal="true" className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4" role="dialog"><form className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-xl bg-white p-6 shadow-xl" onSubmit={submit}><h2 className="text-lg font-semibold text-slate-950">Adicionar documento</h2><p className="mt-2 text-sm text-slate-600">{evidenceType==="signed_contract"?"Contrato assinado":"Primeiro boleto pago"}. O registro documental não altera o contrato nem produz efeito financeiro.</p><div className="mt-5 grid gap-4">{evidenceType==="signed_contract"?<SignedFields/>:<InstallmentFields administratorName={administratorName} hasAdministrator={Boolean(administratorId)}/>}<Field label="Arquivo"><input accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png" className="block w-full text-sm" disabled={missingAdministrator} name="file" required type="file"/></Field></div>{missingAdministrator?<p aria-live="polite" className="mt-4 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-950" role="alert">Este contrato não possui administradora vinculada.</p>:null}{message?<p aria-live="polite" className="mt-4 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-950" role="alert">{message}</p>:null}<div className="mt-6 flex justify-end gap-2"><button className="rounded-md border border-slate-300 px-4 py-2 text-sm font-semibold" disabled={submitting} onClick={onClose} type="button">Cancelar</button><button className="rounded-md bg-slate-900 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60" disabled={submitting||missingAdministrator} type="submit">{submitting?"Enviando...":"Enviar documento"}</button></div></form></div>;
}
function SignedFields(){return <><Field label="Forma de assinatura"><input autoFocus className={inputClass} name="signatureMethod" required/></Field><Field label="Versão do documento (opcional)"><input className={inputClass} name="documentVersion"/></Field><Field label="Plataforma ou provedor de assinatura (opcional)"><input className={inputClass} name="providerName"/></Field><Field label="Referência externa da assinatura (opcional)"><input className={inputClass} name="providerReference"/></Field><Field label="Data efetiva da assinatura"><input className={inputClass} name="effectiveSignedAt" required type="datetime-local"/></Field><Field label="Nome do signatário"><input className={inputClass} name="signatoryName" required/></Field></>}
function InstallmentFields({administratorName,hasAdministrator}:{administratorName:string;hasAdministrator:boolean}){return <><div className="rounded-lg border border-slate-200 bg-slate-50 p-3"><p className="text-xs font-semibold uppercase tracking-[0.08em] text-slate-500">Administradora</p><p className="mt-1 text-sm font-medium text-slate-900">{hasAdministrator?administratorName:"Não vinculada"}</p></div><Field label="Identificador ou referência do boleto"><input autoFocus className={inputClass} name="billingReference" required/></Field><Field label="Valor pago (R$)"><input className={inputClass} min="0.01" name="amount" required step="0.01" type="number"/></Field><Field label="Vencimento"><input className={inputClass} name="dueAt" required type="datetime-local"/></Field><Field label="Data do pagamento"><input className={inputClass} name="paidAt" required type="datetime-local"/></Field><Field label="Referência da confirmação do pagamento (opcional)"><input className={inputClass} name="confirmationReference"/></Field></>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="grid gap-1 text-sm font-medium text-slate-800"><span>{label}</span>{children}</label>}
const inputClass="rounded-md border border-slate-300 px-3 py-2 text-sm focus:border-slate-500 focus:outline-none focus:ring-2 focus:ring-slate-300";
function text(data:FormData,key:string){return String(data.get(key)??"").trim()}
function nullable(data:FormData,key:string){return text(data,key)||null}
function iso(data:FormData,key:string){const value=text(data,key);const parsed=new Date(value);if(!value||Number.isNaN(parsed.getTime()))throw new Error("Informe datas válidas.");return parsed.toISOString()}
export function amountToCents(value:string){const amount=Number(value.replace(",","."));if(!Number.isFinite(amount)||amount<=0)return 0;return Math.round(amount*100)}
export function buildInput(evidenceType:UploadType,data:FormData,administratorId:string|null):EvidenceUploadInput{const file=data.get("file");if(!(file instanceof File)||file.size===0)throw new Error("Selecione um arquivo não vazio.");if(evidenceType==="signed_contract"){const eventAt=iso(data,"effectiveSignedAt");return{evidenceType,eventAt,file,detail:{signatureMethod:text(data,"signatureMethod"),documentVersion:nullable(data,"documentVersion"),providerName:nullable(data,"providerName"),providerReference:nullable(data,"providerReference"),effectiveSignedAt:eventAt,signatories:[{name:text(data,"signatoryName")}]} };}if(!administratorId)throw new Error("Este contrato não possui administradora vinculada.");const eventAt=iso(data,"paidAt"),amountCents=amountToCents(text(data,"amount"));if(!amountCents)throw new Error("Informe um valor pago válido.");return{evidenceType,eventAt,file,detail:{administratorId,billingReference:text(data,"billingReference"),amountCents,currency:"BRL",dueAt:iso(data,"dueAt"),paidAt:eventAt,confirmationReference:nullable(data,"confirmationReference")}};}
