"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {ContractEvidenceClientError,createEvidenceIntentKey,downloadContractEvidence,fetchContractEvidences,validateContractEvidence} from "@/modules/contracts/contract-evidence-client";
import {buildContractEvidenceRequirements,summarizeEvidenceRequirements} from "@/modules/contracts/contract-evidence-presenter";
import type {ContractEvidenceReadModel,ContractEvidenceRequirement,ContractEvidenceType} from "@/modules/contracts/contract-evidence-read-model";
import {ContractEvidenceUploadDialog} from "./contract-evidence-upload-dialog";
import {ContractEvidenceSupersedeDialog} from "./contract-evidence-supersede-dialog";
import {EvidenceLifecycleDialog} from "./evidence-lifecycle-dialog";
import {EvidenceRequirementCard} from "./evidence-requirement-card";

type UploadType=Extract<ContractEvidenceType,"signed_contract"|"first_installment_payment">;
export function ContractEvidencePanel({administratorId,administratorName,contractId}:{administratorId:string|null;administratorName:string;contractId:string}){
  const [evidences,setEvidences]=useState<ContractEvidenceReadModel[]>([]),[canWrite,setCanWrite]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null),[downloadingId,setDownloadingId]=useState<string|null>(null),[mutatingId,setMutatingId]=useState<string|null>(null),[uploadType,setUploadType]=useState<UploadType|null>(null),[invalidating,setInvalidating]=useState<ContractEvidenceReadModel|null>(null),[superseding,setSuperseding]=useState<Extract<ContractEvidenceReadModel,{type:UploadType}>|null>(null);
  const requestRef=useRef(0),contractRef=useRef(contractId),validateKeys=useRef(new Map<string,string>());
  const load=useCallback(async(expectedContractId=contractId)=>{const request=++requestRef.current;setLoading(true);setError(null);try{const next=await fetchContractEvidences(expectedContractId);if(request===requestRef.current&&contractRef.current===expectedContractId){setEvidences(next.evidences);setCanWrite(next.capabilities.canWriteEvidence)}}catch(cause){if(request===requestRef.current&&contractRef.current===expectedContractId)setError(cause instanceof Error?cause.message:"Não foi possível carregar os documentos.")}finally{if(request===requestRef.current&&contractRef.current===expectedContractId)setLoading(false)}},[contractId]);
  useEffect(()=>{contractRef.current=contractId;const timer=window.setTimeout(()=>{setUploadType(null);setInvalidating(null);setSuperseding(null);setMutatingId(null);setMessage(null);validateKeys.current.clear();void load(contractId)},0);return()=>{window.clearTimeout(timer);requestRef.current+=1}},[contractId,load]);
  const requirements=buildContractEvidenceRequirements(evidences),summary=summarizeEvidenceRequirements(requirements);
  async function download(evidence:ContractEvidenceReadModel){const origin=contractId;if(!evidence.documentDownloadPath||downloadingId)return;setDownloadingId(evidence.evidenceId);setMessage(null);try{await downloadContractEvidence(evidence.documentDownloadPath);if(contractRef.current===origin)setMessage("Download iniciado com segurança.")}catch(cause){if(contractRef.current===origin)setMessage(cause instanceof Error?cause.message:"Não foi possível baixar o documento.")}finally{if(contractRef.current===origin)setDownloadingId(null)}}
  async function validate(evidence:ContractEvidenceReadModel){const origin=contractId;if(mutatingId)return;const key=validateKeys.current.get(evidence.evidenceId)??createEvidenceIntentKey();validateKeys.current.set(evidence.evidenceId,key);setMutatingId(evidence.evidenceId);setMessage(null);try{const result=await validateContractEvidence(origin,evidence.evidenceId,key);if(contractRef.current!==origin)return;if(result.kind==="outcome_unknown"){setMessage(result.message);await load(origin);return;}validateKeys.current.delete(evidence.evidenceId);setMessage("Evidência validada.");await load(origin);}catch(cause){if(contractRef.current!==origin)return;setMessage(cause instanceof Error?cause.message:"Não foi possível validar a evidência.");if(cause instanceof ContractEvidenceClientError&&cause.status===409)await load(origin);}finally{if(contractRef.current===origin)setMutatingId(null)}}
  function chooseUpload(requirement:ContractEvidenceRequirement){if(requirement.reserved)return;if(requirement.type==="signed_contract"||requirement.type==="first_installment_payment")setUploadType(requirement.type)}
  async function refresh(origin:string){await load(origin)}
  async function confirmed(origin:string){if(contractRef.current!==origin)return;setUploadType(null);setInvalidating(null);setSuperseding(null);setMessage("Operação documental confirmada.");await load(origin)}
  return <section aria-labelledby="contract-documents-title" className="grid gap-5"><div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold text-slate-950" id="contract-documents-title">Documentos do contrato</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Consulta e gestão de evidências privadas. A presença de evidência não altera a situação do contrato nem produz efeito financeiro.</p></div><div aria-live="polite">{loading?<p className="rounded-xl border border-dashed border-slate-300 bg-white p-5 text-sm text-slate-600">Carregando documentos...</p>:null}{error?<div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-900" role="alert"><p>{error}</p><button className="mt-3 rounded-md border border-rose-300 bg-white px-3 py-2 font-semibold" onClick={()=>void load(contractId)} type="button">Tentar novamente</button></div>:null}{message?<p className="rounded-xl border border-slate-200 bg-white p-3 text-sm text-slate-700">{message}</p>:null}</div>{!loading&&!error?<><section aria-label="Síntese documental" className="grid gap-3 sm:grid-cols-3"><Metric label="Validadas" value={summary.validated}/><Metric label="Aguardando validação" value={summary.awaitingValidation}/><Metric label="Pendentes" value={summary.pending}/></section><div className="grid items-start gap-4 md:grid-cols-2 2xl:grid-cols-3">{requirements.map(requirement=><EvidenceRequirementCard requirement={requirement} downloadingId={downloadingId} mutatingId={mutatingId} canWrite={canWrite} key={requirement.type} onDownload={evidence=>void download(evidence)} onUpload={chooseUpload} onValidate={evidence=>void validate(evidence)} onInvalidate={setInvalidating} onSupersede={evidence=>{if(evidence.type==="signed_contract"||evidence.type==="first_installment_payment")setSuperseding(evidence)}}/>)}</div></>:null}{uploadType?<ContractEvidenceUploadDialog administratorId={administratorId} administratorName={administratorName} contractId={contractId} evidenceType={uploadType} onClose={()=>setUploadType(null)} onRefresh={refresh} onConfirmed={confirmed}/>:null}{invalidating?<EvidenceLifecycleDialog contractId={contractId} evidenceId={invalidating.evidenceId} onClose={()=>setInvalidating(null)} onRefresh={refresh} onConfirmed={confirmed}/>:null}{superseding?<ContractEvidenceSupersedeDialog administratorId={administratorId} administratorName={administratorName} contractId={contractId} evidence={superseding} onClose={()=>setSuperseding(null)} onRefresh={refresh} onConfirmed={confirmed}/>:null}</section>;
}
function Metric({label,value}:{label:string;value:number}){return <article className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold text-slate-950">{value}</p></article>}
