"use client";
import {useState,type FormEvent} from "react";
import {ContractEvidenceClientError,createEvidenceIntentKey,supersedeContractEvidence} from "@/modules/contracts/contract-evidence-client";
import type {ContractEvidenceReadModel} from "@/modules/contracts/contract-evidence-read-model";
import {buildInput} from "./contract-evidence-upload-dialog";

type SupersedableEvidence=Extract<ContractEvidenceReadModel,{type:"signed_contract"|"first_installment_payment"}>;
export function ContractEvidenceSupersedeDialog({administratorId,administratorName,contractId,evidence,onClose,onRefresh,onConfirmed}:{administratorId:string|null;administratorName:string;contractId:string;evidence:SupersedableEvidence;onClose:()=>void;onRefresh:(contractId:string)=>Promise<void>;onConfirmed:(contractId:string)=>Promise<void>}){
  const [idempotencyKey]=useState(createEvidenceIntentKey),[submitting,setSubmitting]=useState(false),[message,setMessage]=useState<string|null>(null),missingAdministrator=evidence.type==="first_installment_payment"&&!administratorId;
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(submitting)return;const data=new FormData(event.currentTarget),reason=String(data.get("reason")??"").trim();if(reason.length<3){setMessage("Informe um motivo com pelo menos 3 caracteres.");return;}if(reason.length>1000){setMessage("O motivo deve ter no máximo 1.000 caracteres.");return;}if(missingAdministrator){setMessage("Este contrato não possui administradora vinculada.");return;}setSubmitting(true);setMessage(null);try{const upload=buildInput(evidence.type,data,administratorId);const result=await supersedeContractEvidence(contractId,evidence.evidenceId,{eventAt:upload.eventAt,detail:upload.detail,file:upload.file,reason},idempotencyKey);if(result.kind==="outcome_unknown"){setMessage("O resultado da substituição precisa ser verificado. A lista foi atualizada; tente novamente com segurança se a versão corrente não mudar.");await onRefresh(contractId);return;}await onConfirmed(contractId);}catch(cause){setMessage(cause instanceof Error?cause.message:"Não foi possível substituir o documento.");if(cause instanceof ContractEvidenceClientError&&cause.status===409)await onRefresh(contractId);}finally{setSubmitting(false)}}
  return <div aria-modal="true" className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4" role="dialog"><form className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-xl bg-white p-6 shadow-xl" onSubmit={submit}><h2 className="text-lg font-semibold text-slate-950">Substituir documento</h2><div className="mt-2 grid gap-2 text-sm leading-6 text-slate-600"><p>O documento atual será preservado no histórico e uma nova versão será criada como evidência corrente.</p><p className="font-medium text-amber-900">A nova versão ficará aguardando validação. A validação anterior não será transferida.</p><p>A substituição não altera a situação do contrato nem produz efeito financeiro.</p></div><div className="mt-5 grid gap-4"><Field label="Motivo"><textarea autoFocus className={`${inputClass} min-h-24`} maxLength={1000} minLength={3} name="reason" required/></Field>{evidence.type==="signed_contract"?<SignedFields evidence={evidence}/>:<InstallmentFields administratorName={administratorName} evidence={evidence} hasAdministrator={Boolean(administratorId)}/>}<Field label="Arquivo"><input accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png" className="block w-full text-sm" disabled={missingAdministrator} name="file" required type="file"/></Field></div>{missingAdministrator?<p className="mt-4 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-950" role="alert">Este contrato não possui administradora vinculada.</p>:null}{message?<p aria-live="polite" className="mt-4 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-950" role="alert">{message}</p>:null}<div className="mt-6 flex justify-end gap-2"><button className="rounded-md border border-slate-300 px-4 py-2 text-sm font-semibold" disabled={submitting} onClick={onClose} type="button">Cancelar</button><button className="rounded-md bg-slate-900 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60" disabled={submitting||missingAdministrator} type="submit">{submitting?"Substituindo...":"Confirmar substituição"}</button></div></form></div>;
}
function SignedFields({evidence}:{evidence:Extract<SupersedableEvidence,{type:"signed_contract"}>}){const signatory=typeof evidence.detail.signatories[0]?.name==="string"?evidence.detail.signatories[0].name:"";return <><Field label="Forma de assinatura"><input className={inputClass} defaultValue={evidence.detail.signatureMethod} name="signatureMethod" required/></Field><Field label="Versão do documento (opcional)"><input className={inputClass} defaultValue={evidence.detail.documentVersion??""} name="documentVersion"/></Field><Field label="Plataforma ou provedor de assinatura (opcional)"><input className={inputClass} defaultValue={evidence.detail.providerName??""} name="providerName"/></Field><Field label="Referência externa da assinatura (opcional)"><input className={inputClass} defaultValue={evidence.detail.providerReference??""} name="providerReference"/></Field><Field label="Data efetiva da assinatura"><input className={inputClass} name="effectiveSignedAt" required type="datetime-local"/></Field><Field label="Nome do signatário"><input className={inputClass} defaultValue={signatory} name="signatoryName" required/></Field></>}
function InstallmentFields({administratorName,evidence,hasAdministrator}:{administratorName:string;evidence:Extract<SupersedableEvidence,{type:"first_installment_payment"}>;hasAdministrator:boolean}){return <><div className="rounded-lg border border-slate-200 bg-slate-50 p-3"><p className="text-xs font-semibold uppercase tracking-[0.08em] text-slate-500">Administradora</p><p className="mt-1 text-sm font-medium text-slate-900">{hasAdministrator?administratorName:"Não vinculada"}</p></div><Field label="Identificador ou referência do boleto"><input className={inputClass} defaultValue={evidence.detail.billingReference} name="billingReference" required/></Field><Field label="Valor pago (R$)"><input className={inputClass} defaultValue={(evidence.detail.amountCents/100).toFixed(2)} min="0.01" name="amount" required step="0.01" type="number"/></Field><Field label="Vencimento"><input className={inputClass} name="dueAt" required type="datetime-local"/></Field><Field label="Data do pagamento"><input className={inputClass} name="paidAt" required type="datetime-local"/></Field><Field label="Referência da confirmação do pagamento (opcional)"><input className={inputClass} defaultValue={evidence.detail.confirmationReference??""} name="confirmationReference"/></Field></>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="grid gap-1 text-sm font-medium text-slate-800"><span>{label}</span>{children}</label>}
const inputClass="rounded-md border border-slate-300 px-3 py-2 text-sm focus:border-slate-500 focus:outline-none focus:ring-2 focus:ring-slate-300";
