import {formatEvidenceDate,formatEvidenceFileSize,formatEvidenceMoney,safeSignatoryNames} from "@/modules/contracts/contract-evidence-presenter";
import type {ContractEvidenceReadModel} from "@/modules/contracts/contract-evidence-read-model";

export function EvidenceCurrentDocument({evidence,isDownloading,onDownload,canWrite=false,isMutating=false,onValidate,onInvalidate,onSupersede}:{evidence:ContractEvidenceReadModel;isDownloading:boolean;onDownload:(evidence:ContractEvidenceReadModel)=>void;canWrite?:boolean;isMutating?:boolean;onValidate?:(evidence:ContractEvidenceReadModel)=>void;onInvalidate?:(evidence:ContractEvidenceReadModel)=>void;onSupersede?:(evidence:ContractEvidenceReadModel)=>void}){
  return <div className="mt-4 rounded-lg border border-slate-200 bg-slate-50 p-4">
    <dl className="grid gap-3 text-sm sm:grid-cols-2"><Datum label="Data do evento" value={formatEvidenceDate(evidence.eventAt)}/><Datum label="Registrada em" value={formatEvidenceDate(evidence.recordedAt)}/><Datum label="Validação" value={evidence.validatedAt?formatEvidenceDate(evidence.validatedAt):"Ainda não validada"}/>{evidence.reference?<Datum label="Referência" value={evidence.reference}/>:null}</dl>
    <BusinessDetails evidence={evidence}/>
    {evidence.hasDocument?<div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-md bg-white p-3"><div><p className="text-sm font-medium text-slate-900">Documento disponível</p><p className="text-xs text-slate-500">{evidence.mediaType??"Tipo não informado"} · {formatEvidenceFileSize(evidence.fileSize)}</p></div>{evidence.canDownloadDocument&&evidence.documentDownloadPath?<button className="rounded-md border border-slate-300 bg-white px-3 py-2 text-sm font-semibold text-slate-800 disabled:opacity-60" disabled={isDownloading||isMutating} onClick={()=>onDownload(evidence)} type="button">{isDownloading?"Baixando...":"Baixar documento"}</button>:null}</div>:<p className="mt-4 text-sm text-slate-500">Nenhum arquivo disponível para download.</p>}
    {canWrite&&evidence.isCurrent&&(evidence.status==="recorded"||evidence.status==="validated")?<div className="mt-4 flex flex-wrap gap-2">{evidence.status==="recorded"&&onValidate?<button className="rounded-md bg-emerald-700 px-3 py-2 text-sm font-semibold text-white disabled:opacity-60" disabled={isMutating} onClick={()=>onValidate(evidence)} type="button">{isMutating?"Processando...":"Validar"}</button>:null}{onInvalidate?<button className="rounded-md border border-rose-300 bg-white px-3 py-2 text-sm font-semibold text-rose-800 disabled:opacity-60" disabled={isMutating} onClick={()=>onInvalidate(evidence)} type="button">Invalidar</button>:null}{onSupersede&&evidence.type!=="patrion_commission_receipt"?<button className="rounded-md border border-slate-300 bg-white px-3 py-2 text-sm font-semibold text-slate-800 disabled:opacity-60" disabled={isMutating} onClick={()=>onSupersede(evidence)} type="button">Substituir documento</button>:null}</div>:null}
  </div>;
}
function BusinessDetails({evidence}:{evidence:ContractEvidenceReadModel}){if(evidence.type==="signed_contract"){const names=safeSignatoryNames(evidence.detail.signatories);return <dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><Datum label="Modalidade" value={evidence.detail.signatureMethod}/><Datum label="Versão" value={evidence.detail.documentVersion??"Não informada"}/><Datum label="Assinatura efetiva" value={formatEvidenceDate(evidence.detail.effectiveSignedAt)}/><Datum label="Signatários" value={names.length?names.join(", "):"Não informados"}/>{evidence.detail.providerName?<Datum label="Provedor" value={evidence.detail.providerName}/>:null}</dl>}
  if(evidence.type==="first_installment_payment")return <dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><Datum label="Valor pago" value={formatEvidenceMoney(evidence.detail.amountCents)}/><Datum label="Referência do boleto" value={evidence.detail.billingReference}/><Datum label="Vencimento" value={formatEvidenceDate(evidence.detail.dueAt)}/><Datum label="Pagamento" value={formatEvidenceDate(evidence.detail.paidAt)}/>{evidence.detail.confirmationReference?<Datum label="Confirmação" value={evidence.detail.confirmationReference}/>:null}</dl>;
  return <dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><Datum label="Valor recebido" value={formatEvidenceMoney(evidence.detail.amountCents)}/><Datum label="Valor atribuível" value={formatEvidenceMoney(evidence.detail.attributableAmountCents)}/><Datum label="Recebimento" value={formatEvidenceDate(evidence.detail.receivedAt)}/><Datum label="Competência" value={evidence.detail.competenceDate}/>{evidence.detail.receiptReference?<Datum label="Referência" value={evidence.detail.receiptReference}/>:null}</dl>;
}
function Datum({label,value}:{label:string;value:string}){return <div><dt className="text-xs font-semibold uppercase tracking-[0.08em] text-slate-500">{label}</dt><dd className="mt-1 break-words font-medium text-slate-900">{value}</dd></div>}
