"use client";
import {useState,type FormEvent} from "react";
import {ContractEvidenceClientError,createEvidenceIntentKey,invalidateContractEvidence} from "@/modules/contracts/contract-evidence-client";

export function EvidenceLifecycleDialog({contractId,evidenceId,onClose,onRefresh,onConfirmed}:{contractId:string;evidenceId:string;onClose:()=>void;onRefresh:(contractId:string)=>Promise<void>;onConfirmed:(contractId:string)=>Promise<void>}){
  const [idempotencyKey]=useState(createEvidenceIntentKey),[submitting,setSubmitting]=useState(false),[message,setMessage]=useState<string|null>(null);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(submitting)return;const reason=String(new FormData(event.currentTarget).get("reason")??"").trim();if(!reason){setMessage("Informe o motivo da invalidação.");return;}setSubmitting(true);setMessage(null);try{const result=await invalidateContractEvidence(contractId,evidenceId,reason,idempotencyKey);if(result.kind==="outcome_unknown"){setMessage(result.message);await onRefresh(contractId);return;}await onConfirmed(contractId);}catch(cause){setMessage(cause instanceof Error?cause.message:"Não foi possível invalidar a evidência.");if(cause instanceof ContractEvidenceClientError&&cause.status===409)await onRefresh(contractId);}finally{setSubmitting(false)}}
  return <div aria-modal="true" className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4" role="dialog"><form className="w-full max-w-xl rounded-xl bg-white p-6 shadow-xl" onSubmit={submit}><h2 className="text-lg font-semibold text-slate-950">Invalidar evidência</h2><p className="mt-2 text-sm leading-6 text-slate-600">A evidência deixará de ser corrente, mas seu documento e o motivo serão preservados no histórico.</p><label className="mt-5 grid gap-1 text-sm font-medium text-slate-800"><span>Motivo</span><textarea autoFocus className="min-h-28 rounded-md border border-slate-300 px-3 py-2" maxLength={1000} name="reason" required/></label>{message?<p aria-live="polite" className="mt-4 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-950" role="alert">{message}</p>:null}<div className="mt-6 flex justify-end gap-2"><button className="rounded-md border border-slate-300 px-4 py-2 text-sm font-semibold" disabled={submitting} onClick={onClose} type="button">Cancelar</button><button className="rounded-md bg-rose-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60" disabled={submitting} type="submit">{submitting?"Invalidando...":"Confirmar invalidação"}</button></div></form></div>;
}
