import assert from "node:assert/strict";
import test from "node:test";
import { buildCommercialProposalSavedSnapshotV1, calculateCommercialTermsHash, parseCommercialProposalSavedSnapshot, validateCommercialProposalSavedSnapshotV1, type CommercialProposalSavedSnapshotV1 } from "./snapshot-v1.ts";

const money = (amountCents: number) => ({ amountCents, currency: "BRL" as const });
function rodobens(): CommercialProposalSavedSnapshotV1 {
  const phases = [
    { phaseKey: "months-1-12", startInstallment: 1, endInstallment: 12, installmentAmount: money(91633) },
    { phaseKey: "months-13-24", startInstallment: 13, endInstallment: 24, installmentAmount: money(109493) },
    { phaseKey: "months-25-216", startInstallment: 25, endInstallment: 216, installmentAmount: money(130793) },
  ];
  const composition = [1,2,3].map(position => ({ itemKey: `strategy-item-${position}`, position, displayLabel: `Cota comercial ${position}`, commercialCatalogCode: "29.09.5526", credit: money(20000000), termMonths: 216, installmentPhases: structuredClone(phases), insurance: { included: true, description: "Seguro incluso" }, adjustment: { index: "INCC", periodicity: "annual" as const, firstAdjustmentInstallment: 14, projectionApplied: false }, contemplation: { scenarioInstallment: 36 + position, isGuarantee: false as const, rules: ["Cenario nao constitui garantia"] } }));
  return { schemaVersion: "commercial-proposal/v1", proposalKind: "patrimonial_strategy", provenance: { authority: "server_derived", simulationId: null, strategyId: null, strategyVersion: "STR-003", calculationEngineKey: "engine:reference-capital-exclusive-2227", calculationEngineVersion: "1.0.0", financialProductKey: "reference_capital_exclusive_2227", financialProductVersion: "2227-IMV115-PCRED-v1", sourceSuggestionId: null }, parties: { customerId: null, customerDisplayName: "Cliente", consultantDisplayName: "Consultor visual" }, product: { productKey: "reference_capital_exclusive_2227", productVersion: "2227-IMV115-PCRED-v1", displayName: "Grupo Exclusivo Referencia Capital", administratorTechnicalId: null, administratorReferenceKey: "rodobens", administratorDisplayName: "Rodobens", groupCode: "2227", modelCode: "IMV115-PCRED", termMonths: 216 }, strategy: { quotaCount: 3, totalCredit: money(60000000), consolidatedInstallmentPhases: phases.map(p=>({ ...p, installmentAmount: money(p.installmentAmount.amountCents * 3) })) }, composition, commercialTerms: { conditions: ["Sujeito ao regulamento"] }, disclosures: [{ disclosureKey: "contemplation-not-guaranteed", category: "material_term", text: "Contemplacao nao garantida" }], presentationReference: { publicationId: "pub-1", publicationVersion: 1 } };
}

test("accepts the Rodobens 2227 three-quota V1 snapshot", () => assert.deepEqual(validateCommercialProposalSavedSnapshotV1(rodobens()), { valid: true }));
test("builder orders composition deterministically", () => { const v=rodobens(); v.composition.reverse(); assert.deepEqual(buildCommercialProposalSavedSnapshotV1(v).composition.map(i=>i.position), [1,2,3]); });
test("rejects duplicate item keys", () => { const v=rodobens(); v.composition[1].itemKey=v.composition[0].itemKey; const r=validateCommercialProposalSavedSnapshotV1(v); assert.equal(r.valid,false); if(!r.valid) assert.ok(r.errors.some(e=>e.code==="CP_COMPOSITION_ITEM_DUPLICATE")); });
test("rejects divergent credit and consolidated installments", () => { const v=rodobens(); v.strategy.totalCredit.amountCents--; v.strategy.consolidatedInstallmentPhases[0].installmentAmount.amountCents--; const r=validateCommercialProposalSavedSnapshotV1(v); assert.equal(r.valid,false); if(!r.valid) assert.ok(r.errors.some(e=>e.code==="CP_CREDIT_TOTAL_MISMATCH") && r.errors.some(e=>e.code==="CP_INSTALLMENT_TOTAL_MISMATCH")); });
test("rejects overlap, inconsistent term, fractional cents and missing fields", () => { const v=rodobens(); v.composition[0].installmentPhases[1].startInstallment=12; v.composition[1].termMonths=215; v.composition[2].credit.amountCents=1.5; delete (v.product as Partial<typeof v.product>).productKey; assert.equal(validateCommercialProposalSavedSnapshotV1(v).valid,false); });
test("parser distinguishes legacy and unsupported schema without conversion", () => { assert.equal(parseCommercialProposalSavedSnapshot({ old: true }).kind,"legacy"); assert.equal(parseCommercialProposalSavedSnapshot({ schemaVersion:"commercial-proposal/v2" }).kind,"unsupported"); });
test("hash is deterministic, material changes affect it and visual changes do not", () => { const a=rodobens(), b=rodobens(); b.presentationReference={publicationId:"different",publicationVersion:99}; b.parties.consultantDisplayName="Outro"; assert.equal(calculateCommercialTermsHash(a),calculateCommercialTermsHash(b)); b.composition[0].credit.amountCents++; assert.notEqual(calculateCommercialTermsHash(a),calculateCommercialTermsHash(b)); });
