-- Sprint 101B.26
-- Controlled removal package: authenticated bridge update only
-- Manual execution only. Codex must not execute this file.
--
-- Target policy:
--   Authenticated bridge update crm_leads
--
-- Protected policies:
--   Allow public read crm_leads
--   Allow public update crm_leads
--   crm_leads authenticated read same organization
--   crm_leads authenticated update same organization
--
-- Already retired and not recreated here:
--   Authenticated bridge read crm_leads
drop policy if exists "Authenticated bridge update crm_leads" on public.crm_leads;
