import assert from "node:assert/strict";import test from "node:test";import {readFileSync} from "node:fs";import {join} from "node:path";
const read=(path:string)=>readFileSync(join(process.cwd(),path),"utf8"),panel=read("components/contracts/evidence/contract-evidence-panel.tsx"),workspace=read("components/operations/contracts/operations-contract-workspace.tsx"),route=read("app/operations/contracts/[contractId]/page.tsx"),client=read("modules/contracts/contract-evidence-client.ts"),server=read("modules/contracts/contract-evidence-ingestion-server.ts"),proposal=read("components/contracts/proposal-materialization-panel.tsx"),lead=read("components/crm/lead-contracts-card.tsx"),evidenceComponents=[panel,read("components/contracts/evidence/evidence-requirement-card.tsx"),read("components/contracts/evidence/evidence-current-document.tsx"),read("components/contracts/evidence/evidence-history.tsx")].join("\n");
test("surface is read-only and renders loading retry and three requirements",()=>{assert.match(panel,/Carregando documentos/);assert.match(panel,/Tentar novamente/);for(const forbidden of ["FormData","type=\"file\"","changeContractEvidenceStatus","supersedeContractEvidence","service.role","service_role"])assert.doesNotMatch(evidenceComponents,new RegExp(forbidden,"i"))});
test("GET is typed and enrichment exposes no internal evidence fields",()=>{assert.match(server,/ContractEvidenceReadModel\[\]/);assert.match(server,/contract_evidence_audit_events/);for(const forbidden of ["storage_bucket","storage_object_path","content_sha256","event_hash","idempotency_key"])assert.doesNotMatch(server.slice(server.indexOf("export async function listContractEvidences"),server.indexOf("export async function changeContractEvidenceStatus")),new RegExp(forbidden))});
test("download is authenticated relative and always revokes its object URL",()=>{assert.match(client,/Authorization:`Bearer \$\{token\}`/);assert.match(client,/isRelativeDocumentPath/);assert.match(client,/URL\.revokeObjectURL\(url\)/);assert.doesNotMatch(client,/window\.open|createSignedUrl|getPublicUrl/)});
test("documents tab is allow-listed and keyboard-semantic",()=>{assert.match(route,/tab === "documents"/);assert.match(workspace,/role="tablist"/);assert.match(workspace,/role="tab"/);assert.match(workspace,/aria-selected/);assert.match(workspace,/ContractEvidencePanel/)});
test("all active roles receive the same read surface and contract changes trigger a new GET",()=>{assert.doesNotMatch(evidenceComponents,/master|admin|sdr/);assert.match(panel,/useCallback/);assert.match(panel,/\[contractId\]/);assert.match(panel,/requestRef\.current/)});
test("proposal and lead provide document shortcuts without duplicating evidence UI",()=>{assert.match(proposal,/tab=documents&origin=proposal/);assert.match(lead,/tab=documents&origin=lead/);assert.doesNotMatch(proposal,/EvidenceRequirementCard/);assert.doesNotMatch(lead,/EvidenceRequirementCard/)});
test("responsive cards avoid horizontal tables and expose accessible history",()=>{assert.match(panel,/md:grid-cols-2 2xl:grid-cols-3/);assert.match(read("components/contracts/evidence/evidence-history.tsx"),/<details/);assert.doesNotMatch(panel,/<table/)});
