import {requireSupabaseAccessToken} from "../access/supabase-session-token.ts";
import type {ContractEvidenceReadModel} from "./contract-evidence-read-model";

export class ContractEvidenceClientError extends Error{readonly code:string;constructor(code:string,message:string){super(message);this.code=code;this.name="ContractEvidenceClientError";}}
export async function fetchContractEvidences(contractId:string){const token=await requireSupabaseAccessToken("Sessão inválida para consultar documentos.");const response=await fetch(`/api/contracts/${encodeURIComponent(contractId)}/evidences`,{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});const payload=await safeJson(response);if(!response.ok||!payload||!Array.isArray(payload.evidences))throw clientError(payload,"Não foi possível carregar os documentos.");return payload.evidences as ContractEvidenceReadModel[];}
export async function downloadContractEvidence(path:string){if(!isRelativeDocumentPath(path))throw new ContractEvidenceClientError("CED_DOCUMENT_NOT_FOUND","Documento não encontrado.");const token=await requireSupabaseAccessToken("Sessão inválida para baixar o documento.");const response=await fetch(path,{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});if(!response.ok)throw clientError(await safeJson(response),"Não foi possível baixar o documento.");return saveEvidenceDownload(response);}
export async function saveEvidenceDownload(response:Response,environment:{document:Pick<Document,"createElement"|"body">;URL:Pick<typeof URL,"createObjectURL"|"revokeObjectURL">}={document,URL}){const blob=await response.blob();const filename=sanitizeDownloadFilename(readFilename(response.headers.get("content-disposition")));const url=environment.URL.createObjectURL(blob);const anchor=environment.document.createElement("a");try{anchor.href=url;anchor.download=filename;anchor.hidden=true;environment.document.body.append(anchor);anchor.click();}finally{anchor.remove();environment.URL.revokeObjectURL(url);}return filename;}
export function sanitizeDownloadFilename(value:string|null){const cleaned=(value??"documento-evidencia").normalize("NFKC").replace(/[\\/:*?"<>|\u0000-\u001f\u007f]/g,"-").replace(/\.+$/g,"").trim().slice(0,180);return cleaned||"documento-evidencia";}
export function isRelativeDocumentPath(value:string){return /^\/api\/contracts\/[0-9a-f-]+\/evidences\/[0-9a-f-]+\/document$/i.test(value);}
function readFilename(value:string|null){if(!value)return null;const encoded=/filename\*=UTF-8''([^;]+)/i.exec(value)?.[1];if(encoded){try{return decodeURIComponent(encoded)}catch{return null}}return /filename="([^"]+)"/i.exec(value)?.[1]??null;}
async function safeJson(response:Response){return response.json().catch(()=>null) as Promise<{code?:string;error?:string;message?:string;evidences?:unknown[]}|null>;}
function clientError(payload:{code?:string;error?:string;message?:string}|null,fallback:string){const code=payload?.error??payload?.code??"CE_READ_FAILED";const messages:Record<string,string>={CED_SESSION_REQUIRED:"Sessão obrigatória.",CED_ACTOR_FORBIDDEN:"Seu perfil não pode acessar este documento.",CED_DOCUMENT_NOT_FOUND:"Documento não encontrado.",CED_DOCUMENT_INTEGRITY_FAILED:"A integridade do documento não pôde ser confirmada.",CED_AUDIT_FAILED:"O acesso não pôde ser auditado.",CE_INTERNAL_UNAVAILABLE:"Serviço documental indisponível."};return new ContractEvidenceClientError(code,messages[code]??fallback);}
