import type {
  CognitiveOperator,
  CollectedContext,
  ExecutiveSituation,
  NormalizedContext,
  OperationalContext,
} from "../../contracts";
import { CollectOperator, NormalizeOperator } from "../../operators";

const collectOperator = CollectOperator as SyncCognitiveOperator<
  OperationalContext,
  CollectedContext
>;
const normalizeOperator = NormalizeOperator as SyncCognitiveOperator<
  CollectedContext,
  NormalizedContext
>;

export const SituationIntegrationPipeline = {
  execute(input: OperationalContext): ExecutiveSituation {
    const collectedContext = collectOperator.execute(input);
    const normalizedContext = normalizeOperator.execute(collectedContext);

    return {
      artifactType: "executive_situation",
      confidence: "UNKNOWN",
      generatedAt: input.generatedAt,
      id: createArtifactId("executive_situation", input),
      leadId: input.leadId,
      metadata: {
        narrative:
          "Structural placeholder only. Semantic cognitive operators are not implemented yet.",
        normalizedContextId: normalizedContext.id,
        placeholder: true,
      },
      organizationId: input.organizationId,
      payload: {
        gaps: [],
        highlights: [],
        risks: [],
        summaryLines: [
          "ExecutiveSituation placeholder generated by structural pipeline.",
        ],
      },
      pipelineVersion: SituationIntegrationPipeline.version,
      sourceOperators: [
        ...normalizedContext.sourceOperators,
        SituationIntegrationPipeline.id,
      ],
    };
  },
  id: "cognitive.pipeline.situation-integration",
  version: "0.1.0",
};

type SyncCognitiveOperator<I, O> = Omit<CognitiveOperator<I, O>, "execute"> & {
  execute: (input: I, context?: OperationalContext) => O;
};

function createArtifactId(prefix: string, context: OperationalContext) {
  return `${prefix}:${context.organizationId}:${context.leadId}:${context.generatedAt}`;
}
