"use client";
import {useState} from "react";
import {createContractActivationIdempotencyKey,executeContractActivation} from "@/modules/contracts/contract-activation-client";
import type {ContractActivationResult,ContractFinancialAuthority} from "@/modules/contracts/contract-activation-types";
import type {ContractStatus} from "@/modules/contracts/types";

type Props={contractId:string;contractLabel:string;currentStatus:ContractStatus;isOpen:boolean;onClose:()=>void;onUpdated?:(result:ContractActivationResult)=>Promise<void>|void};
export function ContractStatusDialog({contractId,contractLabel,currentStatus,isOpen,onClose,onUpdated}:Props){
 const operation=currentStatus==="inactive"?"reactivate":currentStatus==="active"?"deactivate":"activate";
 const [key]=useState(createContractActivationIdempotencyKey),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[result,setResult]=useState<ContractActivationResult|null>(null),[authority,setAuthority]=useState<ContractFinancialAuthority|null>(null);
 if(!isOpen)return null;
 async function submit(selected=authority){setBusy(true);setError(null);try{const next=await executeContractActivation(contractId,{operation,idempotencyKey:key,selectedFinancialAuthority:selected});setResult(next);if(next.resolutionOutcome==="selection_required")return;await onUpdated?.(next);if(next.resolutionOutcome==="resolved"&&next.financialOutcome!=="failed")onClose();}catch(cause){setError(cause instanceof Error?cause.message:"Nao foi possivel alterar a situacao do contrato.");}finally{setBusy(false)}}
 const selection=result?.resolutionOutcome==="selection_required";
 return <div aria-modal="true" className="fixed inset-0 z-50 grid place-items-center bg-slate-950/45 p-4" role="dialog"><div className="w-full max-w-xl rounded-xl bg-white p-5 shadow-xl"><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Situacao do contrato</p><h3 className="mt-2 text-xl font-semibold">{operation==="activate"?"Ativar contrato":operation==="reactivate"?"Reativar contrato":"Inativar contrato"}</h3><p className="mt-2 text-sm text-slate-600">{contractLabel}</p>
 {selection?<fieldset className="mt-5 grid gap-3"><legend className="text-sm font-semibold">Tratamento financeiro</legend>{([['commission_engine','Commission Engine','Usar a configuração de comissão estruturada do contrato.'],['legacy_revenue','Fluxo financeiro existente','Usar o fluxo financeiro anterior já suportado.'],['not_applicable','Sem comissão aplicável','Este contrato não gera comissão automática neste fluxo.']] as const).map(([value,label,help])=><label className="rounded-lg border p-3 text-sm" key={value}><input checked={authority===value} className="mr-2" name="authority" onChange={()=>setAuthority(value)} type="radio"/><b>{label}</b><span className="mt-1 block text-xs text-slate-500">{help}</span></label>)}</fieldset>:null}
 {result?.resolutionOutcome==="reconciliation_required"?<p className="mt-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">O contrato possui registros financeiros conflitantes e precisa de reconciliação antes de novo processamento financeiro.</p>:null}
 {result?.financialOutcome==="failed"?<p className="mt-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">Contrato alterado, mas o processamento financeiro requer atenção.</p>:null}
 {error?<p className="mt-4 rounded-lg bg-rose-50 p-3 text-sm text-rose-900">{error}</p>:null}<div className="mt-6 flex justify-end gap-2"><button className="rounded-md border px-4 py-2 text-sm" disabled={busy} onClick={onClose}>Cancelar</button><button className="rounded-md bg-slate-900 px-4 py-2 text-sm text-white disabled:opacity-50" disabled={busy||(selection&&!authority)} onClick={()=>void submit()}>{busy?"Processando...":selection?"Confirmar tratamento":"Confirmar alteração"}</button></div></div></div>;
}
